services:
  ros2-common: 

    # Network Mode Configuration
    network_mode: host    # Utilize host network stack for seamless communication.

    tty: true

    # Linux Capabilities
    cap_add:
      - SYS_PTRACE        # Allow process tracing capabilities used for debugging, accessing gpu.

    # Security Options
    security_opt:
    - seccomp:unconfined  # Disable Seccomp filtering to allow all system calls for toosl like gdb

    # Environment Variables
    environment:
      # Display
      - DISPLAY=$DISPLAY                # Specify X11 display server.
      - XAUTHORITY=/root/.XAuthority    # Point to X11 authorization file location.

      # ROS
      - ROS_DOMAIN_ID=3                 # Define ROS domain ID for communication.
      - ROS_LOCALHOST_ONLY=1            # Restrict ROS communication to localhost.

    # Volume Configuration
    volumes:
      # Display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw                        # Mounts X11 Socket.
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.XAuthority:rw   # Mounts X11 Authorization file.

      # Graphics card
      - /dev/dri/:/dev/dri/:cached      # Mounting graphic card interfaces.

      # User Source file
      - ../../src/:/root/ws/src:cached  # Syncs the source Directory.