services:

  ros:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - ROS_DISTRO=${ROS_DISTRO}
        - BASE_IMAGE=${BASE_IMAGE}
        - TARGET_LAYER=${TARGET_LAYER}
        - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - WORKSPACE_DIR=${WORKSPACE_DIR}
      target: dev
    
    # Network Mode Configuration
    network_mode: host                        # Utilize host network stack for seamless communication.
    ipc: host                                 # Shared memory transport with host, e.g. rviz GUIs

    # Linux Capabilities
    cap_add:
      - SYS_PTRACE                            # Allow process tracing capabilities to enable debugging, e.g. gdb, accessing gpu.

    # Security Options
    security_opt:
    - seccomp:unconfined                      # Disable Seccomp filtering to allow all system calls for toosl like gdb

    # Environment Variables
    environment:
      # Shell
      - SHELL=/bin/bash
      
      # Display
      - DISPLAY=${DISPLAY}                    # Specify X11 display server.
      - QT_X11_NO_MITSHM=1

      # ROS
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}        # Define ROS domain ID for communication.

    # Volume Configuration
    volumes:
      # Display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw                              # Mounts X11 Socket.

      # SSH
      - ${HOME}/.ssh/:${USER_DIR}/.ssh/                 # Mount ssh keys

      # Bash history
      - ${HOME}.bash_history:${USER_DIR}.bash_history   # Mount bash commands history

      # User Source file
      - ../src/:${WORKSPACE_DIR}/src:cached             # Syncs the source Directory.

    devices:
      # Graphics card
      - /dev/dri/card1:/dev/dri/card1                   # Mounting graphic card interfaces.
      - /dev/dri/renderD128:/dev/dri/renderD128

    command: sleep infinity