services:
  ros2:
    build:
        context: .
        dockerfile: Dockerfile

    # Interactive shell
    stdin_open: true
    tty: true

    network_mode: host

    environment:
      # default shell
      - SHELL=/bin/bash

      # for gui
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/root/.XAuthority

      # for ros2
      - ROS_DOMAIN_ID=3
      - ROS_LOCALHOST_ONLY=1

    volumes:
      # display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw                       ## mount x11 socket
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.XAuthority:rw  ## x11 authorization

      # folder & file sync
      - ../ws/:/root/ws:cache                                  ## source directory (backing up for saftey)
      - ../.devcontainer/:/root/ws/.devcontainer:cache         ## devcontainer configs (for adding dependencies while installation)
      - ../models/:/root/.gazebo/models:cache                  ## gazebo models (to add model faster)
      - ../data/:/root/ws/data:cache                           ## for storing maps, pdfs, etc..