name: Humble

on:
  push:
    branches:
      humble
    paths:
      - .devcontainer/dockerfile
  pull_request:
    branches:
      humble
    paths:
      - .devcontainer/dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: humble

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: manojm003/ros
          tags: |
            type=raw,value=humble-nav2

      - name: Go Build Cache for Docker
        uses: actions/cache@v3
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}

      - name: inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v2.1.2
        with:
          cache-source: go-build-cache

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: manojm003
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            manojm003/ros:humble-nav2